### ISSUE TITLE
Нет доступа к публичным комнатам

### ISSUE THREAD

**Issue by Rammdakk** [teddyzxcv/alias-swift-api#9]
В repspones game-rooms/list-all код доступа приходит только админам, на остальые комнаты его нет.

**Comment by teddyzxcv** [comment]
Решил проблему так: теперь в join-room можно не добавлять invitationCode и реализовано логика:

- Если есть код и комната приватная - допуск к комнату
- Если нет код и комната публичная - допуск к комнату
- Остальные случай - abort
